### PR TITLE
Week2 assignment

### PR DESCRIPTION
**Pull request by CSY-Betty**
陳淑瀅Betty
http://35.73.108.30:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but height of welcome section is too large. Try to meet the design.

**Comment by CSY-Betty** [comment]
陳淑瀅Betty
http://35.73.108.30:3000/

背景圖高度修改完成，再麻煩確認，謝謝！

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Comment by CSY-Betty** [comment]
好的，已按下Re-request review button，再麻煩確認，謝謝！

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
